export interface TransactionReceivePO {
    id?: number; // Optional, since it might be auto-generated by Supabase
    po_number: string;
    reg_number: string;
    description: string;
    qty_order: number;
    rcv_qty: number;
    receive_date: string;
    storesperson: string;
    warehouse: string;
  }
  